

// autogenerated

namespace HeatRange
{
	public static partial class Def 
	{
		public static partial class FP
		{

			public static partial class Sprites
			{
				public const string Asteroid = "resources/sprites/asteroid.png";
				public const string Reactor = "resources/sprites/Reactor.png";
				public const string Ship = "resources/sprites/Ship.png";
			}

		}

	}

}

